- name: install docker
  hosts: _development
  become: true
  roles:
    - docker
  
- name: postgresql config
  hosts: _ansible_postgresql
  become: true
  roles:
    - postgre

- name: nodejs config
  hosts: _ansible_nodejs
  become: true
  roles:
    - nodejs

- name: react config
  hosts: _ansible_react
  become: true
  roles:
    - react